"""新增角色状态字段

Revision ID: aa11bb22cc33
Revises: d4d253e3f4c6
Create Date: 2026-02-12 12:45:13.617928

"""
# pyright: reportAttributeAccessIssue=false, reportDeprecated=false, reportMissingImports=false, reportUnknownArgumentType=false, reportUnknownMemberType=false, reportUnknownParameterType=false, reportUnknownVariableType=false
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa11bb22cc33'
down_revision: Union[str, None] = 'd4d253e3f4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('status', sa.String(length=20), nullable=True, comment='状态：active/deceased/missing/retired/destroyed'))
    op.add_column('characters', sa.Column('status_changed_chapter', sa.Integer(), nullable=True, comment='状态变更的章节号'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'status_changed_chapter')
    op.drop_column('characters', 'status')
    # ### end Alembic commands ###
