export interface TagOption {
  id: string;
  label: string;
}

export interface GenreOption extends TagOption {}

export interface ChannelOption {
  id: string;
  label: string;
  genres: GenreOption[];
}

export type Channel = ChannelOption;

export const MAX_TAGS_PER_DIMENSION = 5;

type TagPrefix = 'theme' | 'char' | 'plot';
type ChannelId = 'nan' | 'nv' | 'erciyuan';

function createTagOption(prefix: TagPrefix, label: string): TagOption {
  return {
    id: `${prefix}_${TAG_SLUGS[prefix][label]}`,
    label,
  };
}

function createGenreOptions(channelId: ChannelId, labels: readonly string[]): GenreOption[] {
  return labels.map(label => ({
    id: `genre_${channelId}_${GENRE_SLUGS[channelId][label]}`,
    label,
  }));
}

const NAN_GENRE_LABELS = [
  '玄幻',
  '奇幻',
  '武侠',
  '仙侠',
  '都市',
  '军事',
  '历史',
  '游戏',
  '体育',
  '科幻',
  '诸天无限',
  '悬疑',
] as const;

const NV_GENRE_LABELS = [
  '古代言情',
  '仙侠奇缘',
  '现代言情',
  '浪漫青春',
  '玄幻言情',
  '悬疑推理',
  '科幻空间',
  '游戏竞技',
  '短篇',
  '轻小说',
] as const;

const ECY_GENRE_LABELS = [
  '原生幻想',
  '恋爱日常',
  '衍生同人',
  '搞笑吐槽',
] as const;

const THEME_LABELS = [
  '历史脑洞',
  '都市种田',
  '都市异能',
  '综影视',
  '都市日常',
  '都市高武',
  '历史古代',
  '都市生活',
  '末日求生',
  '灵气复苏',
  '东方仙侠',
  '西方奇幻',
  '悬疑灵异',
  '轻小说',
  '玄幻脑洞',
  '古代',
  '体育',
  '东方玄幻',
  '男频衍生',
  '高武世界',
  '游戏动漫',
  '影视小说',
  '武侠',
  '架空',
  '规则怪谈',
  '异能',
  '综漫',
  '天灾',
  '宝可梦',
  '悬疑脑洞',
  '开局',
  '宋朝',
  '异世大陆',
  '清朝',
  '搞笑轻松',
  '谍战',
  '克苏鲁',
  '赛博朋克',
  '第四天灾',
  '断层',
  '武将',
  '第一人称',
] as const;

const CHARACTER_LABELS = [
  '多女主',
  '单女主',
  '皇帝',
  '天才',
  '学霸',
  '群像',
  '无女主',
  '大佬',
  '神医',
  '奶爸',
  '反派',
  '特种兵',
  '校花',
  '大小姐',
  '游戏主播',
  '宫廷侯爵',
  '扮猪吃虎',
  '神探',
  '全能',
  '赘婿',
  '特工',
  '战神赘婿',
  '女帝',
  '腹黑',
] as const;

const PLOT_LABELS = [
  '漫威',
  '诸天万界',
  '都市修真',
  '无脑爽',
  '大唐',
  '基建',
  '求生',
  '无限流',
  '三国',
  '职场',
  '修仙',
  '海岛',
  '乡村',
  '直播',
  '废土',
  '动漫衍生',
  '穿越',
  '重生',
  '美食',
  '争霸',
  '盗墓',
  '网游',
  '灵异',
  '明朝',
  '穿书',
  '二次元',
  '九叔',
  '科举',
  '风水秘术',
  '电竞',
  '仙侠',
  '星际',
  '空间',
  '破案',
  '火影',
  '奥特同人',
  '红楼衍生',
  '捉鬼',
  '西游衍生',
  '鉴宝',
  '打脸',
  '囤物资',
  '黑道',
  '家庭',
  '升级流',
  '推理',
  '海贼王',
  '外卖',
  '传统玄幻',
  '封神',
  '神奇宝贝',
  '惊悚游戏',
  '奇幻',
  '大秦',
  '海贼',
  '聊天群',
  '剑道',
  '副本',
  '龙珠',
  '卡牌',
  '都市江湖',
  '剑修',
  '无后宫',
  '斩神衍生',
  '钓鱼',
  '黑化',
  '甄嬛衍生',
  '宠物',
  '双系统',
  '1v1',
  '公版衍生',
  '迪化',
  '斩神',
  '双重生',
  '十日衍生',
  '高手下山',
  '山海经',
  '魂穿',
  '灵魂互换',
  '绝地逃生',
  '如懿衍生',
] as const;

const TAG_SLUGS: Record<TagPrefix, Record<string, string>> = {
  theme: {
    '历史脑洞': 'lishi_naodong',
    '都市种田': 'dushi_zhongtian',
    '都市异能': 'dushi_yineng',
    '综影视': 'zong_yingshi',
    '都市日常': 'dushi_richang',
    '都市高武': 'dushi_gaowu',
    '历史古代': 'lishi_gudai',
    '都市生活': 'dushi_shenghuo',
    '末日求生': 'mori_qiusheng',
    '灵气复苏': 'lingqi_fusu',
    '东方仙侠': 'dongfang_xianxia',
    '西方奇幻': 'xifang_qihuan',
    '悬疑灵异': 'xuanyi_lingyi',
    '轻小说': 'qingxiaoshuo',
    '玄幻脑洞': 'xuanhuan_naodong',
    '古代': 'gudai',
    '体育': 'tiyu',
    '东方玄幻': 'dongfang_xuanhuan',
    '男频衍生': 'nanpin_yansheng',
    '高武世界': 'gaowu_shijie',
    '游戏动漫': 'youxi_dongman',
    '影视小说': 'yingshi_xiaoshuo',
    '武侠': 'wuxia',
    '架空': 'jiakong',
    '规则怪谈': 'guize_guaitan',
    '异能': 'yineng',
    '综漫': 'zongman',
    '天灾': 'tianzai',
    '宝可梦': 'baokemeng',
    '悬疑脑洞': 'xuanyi_naodong',
    '开局': 'kaiju',
    '宋朝': 'songchao',
    '异世大陆': 'yishi_dalu',
    '清朝': 'qingchao',
    '搞笑轻松': 'gaoxiao_qingsong',
    '谍战': 'diezhan',
    '克苏鲁': 'kesulu',
    '赛博朋克': 'saibo_pengke',
    '第四天灾': 'disi_tianzai',
    '断层': 'duanceng',
    '武将': 'wujiang',
    '第一人称': 'diyi_rencheng',
  },
  char: {
    '多女主': 'duo_nvzhu',
    '单女主': 'dan_nvzhu',
    '皇帝': 'huangdi',
    '天才': 'tiancai',
    '学霸': 'xueba',
    '群像': 'qunxiang',
    '无女主': 'wu_nvzhu',
    '大佬': 'dalao',
    '神医': 'shenyi',
    '奶爸': 'naiba',
    '反派': 'fanpai',
    '特种兵': 'tezhongbing',
    '校花': 'xiaohua',
    '大小姐': 'daxiaojie',
    '游戏主播': 'youxi_zhubo',
    '宫廷侯爵': 'gongting_houjue',
    '扮猪吃虎': 'banzhu_chihu',
    '神探': 'shentan',
    '全能': 'quanneng',
    '赘婿': 'zhuixu',
    '特工': 'tegong',
    '战神赘婿': 'zhanshen_zhuixu',
    '女帝': 'nvdi',
    '腹黑': 'fuhei',
  },
  plot: {
    '漫威': 'manwei',
    '诸天万界': 'zhutian_wanjie',
    '都市修真': 'dushi_xiuzhen',
    '无脑爽': 'wunao_shuang',
    '大唐': 'datang',
    '基建': 'jijian',
    '求生': 'qiusheng',
    '无限流': 'wuxianliu',
    '三国': 'sanguo',
    '职场': 'zhichang',
    '修仙': 'xiuxian',
    '海岛': 'haidao',
    '乡村': 'xiangcun',
    '直播': 'zhibo',
    '废土': 'feitu',
    '动漫衍生': 'dongman_yansheng',
    '穿越': 'chuanyue',
    '重生': 'chongsheng',
    '美食': 'meishi',
    '争霸': 'zhengba',
    '盗墓': 'daomu',
    '网游': 'wangyou',
    '灵异': 'lingyi',
    '明朝': 'mingchao',
    '穿书': 'chuanshu',
    '二次元': 'erciyuan',
    '九叔': 'jiushu',
    '科举': 'keju',
    '风水秘术': 'fengshui_mishu',
    '电竞': 'dianjing',
    '仙侠': 'xianxia',
    '星际': 'xingji',
    '空间': 'kongjian',
    '破案': 'poan',
    '火影': 'huoying',
    '奥特同人': 'aote_tongren',
    '红楼衍生': 'honglou_yansheng',
    '捉鬼': 'zhuogui',
    '西游衍生': 'xiyou_yansheng',
    '鉴宝': 'jianbao',
    '打脸': 'dalian',
    '囤物资': 'tunwuzi',
    '黑道': 'heidao',
    '家庭': 'jiating',
    '升级流': 'shengji_liu',
    '推理': 'tuili',
    '海贼王': 'haizeiwang',
    '外卖': 'waimai',
    '传统玄幻': 'chuantong_xuanhuan',
    '封神': 'fengshen',
    '神奇宝贝': 'shenqibaobei',
    '惊悚游戏': 'jingsong_youxi',
    '奇幻': 'qihuan',
    '大秦': 'daqin',
    '海贼': 'haizei',
    '聊天群': 'liaotianqun',
    '剑道': 'jiandao',
    '副本': 'fuben',
    '龙珠': 'longzhu',
    '卡牌': 'kapai',
    '都市江湖': 'dushi_jianghu',
    '剑修': 'jianxiu',
    '无后宫': 'wu_hougong',
    '斩神衍生': 'zhanshen_yansheng',
    '钓鱼': 'diaoyu',
    '黑化': 'heihua',
    '甄嬛衍生': 'zhenhuan_yansheng',
    '宠物': 'chongwu',
    '双系统': 'shuang_xitong',
    '1v1': 'one_on_one',
    '公版衍生': 'gongban_yansheng',
    '迪化': 'dihua',
    '斩神': 'zhanshen',
    '双重生': 'shuang_chongsheng',
    '十日衍生': 'shiri_yansheng',
    '高手下山': 'gaoshou_xiashan',
    '山海经': 'shanhaijing',
    '魂穿': 'hunchuan',
    '灵魂互换': 'linghun_huhuan',
    '绝地逃生': 'juedi_taosheng',
    '如懿衍生': 'ruyi_yansheng',
  },
};

const GENRE_SLUGS: Record<ChannelId, Record<string, string>> = {
  nan: {
    '玄幻': 'xuanhuan',
    '奇幻': 'qihuan',
    '武侠': 'wuxia',
    '仙侠': 'xianxia',
    '都市': 'dushi',
    '军事': 'junshi',
    '历史': 'lishi',
    '游戏': 'youxi',
    '体育': 'tiyu',
    '科幻': 'kehuan',
    '诸天无限': 'zhutian_wuxian',
    '悬疑': 'xuanyi',
  },
  nv: {
    '古代言情': 'gudai_yanqing',
    '仙侠奇缘': 'xianxia_qiyuan',
    '现代言情': 'xiandai_yanqing',
    '浪漫青春': 'langman_qingchun',
    '玄幻言情': 'xuanhuan_yanqing',
    '悬疑推理': 'xuanyi_tuili',
    '科幻空间': 'kehuan_kongjian',
    '游戏竞技': 'youxi_jingji',
    '短篇': 'duanpian',
    '轻小说': 'qingxiaoshuo',
  },
  erciyuan: {
    '原生幻想': 'yuansheng_huanxiang',
    '恋爱日常': 'lianai_richang',
    '衍生同人': 'yansheng_tongren',
    '搞笑吐槽': 'gaoxiao_tucao',
  },
};

export const CHANNELS: Channel[] = [
  {
    id: 'nan',
    label: '男频',
    genres: createGenreOptions('nan', NAN_GENRE_LABELS),
  },
  {
    id: 'nv',
    label: '女频',
    genres: createGenreOptions('nv', NV_GENRE_LABELS),
  },
  {
    id: 'erciyuan',
    label: '二次元',
    genres: createGenreOptions('erciyuan', ECY_GENRE_LABELS),
  },
];

export const THEME_TAGS: TagOption[] = THEME_LABELS.map(label => createTagOption('theme', label));
export const CHARACTER_TAGS: TagOption[] = CHARACTER_LABELS.map(label => createTagOption('char', label));
export const PLOT_TAGS: TagOption[] = PLOT_LABELS.map(label => createTagOption('plot', label));

export function getGenresByChannel(channelId: string): GenreOption[] {
  const channel = CHANNELS.find(item => item.id === channelId);
  return channel ? [...channel.genres] : [];
}
